import 'package:moneyapp/models/mcc_model.dart';

/// Constant MCC Categories
class MCCCategories {
  static const List<Map<String, dynamic>> categories = [
    {
      'id': 1,
      'name': 'Agricultural Services',
      'emoji': '🚜',
      'range': '0001-1499',
    },
    {
      'id': 2,
      'name': 'Contracted Services',
      'emoji': '🏗️',
      'range': '1500-2999',
    },
    {
      'id': 3,
      'name': 'Transportation Services',
      'emoji': '🚗',
      'range': '4000-4799',
    },
    {'id': 4, 'name': 'Utility Services', 'emoji': '💡', 'range': '4800-4999'},
    {
      'id': 5,
      'name': 'Retail Outlet Services',
      'emoji': '🏪',
      'range': '5000-5599',
    },
    {'id': 6, 'name': 'Clothing Stores', 'emoji': '🛍️', 'range': '5600-5699'},
    {
      'id': 7,
      'name': 'Miscellaneous Stores',
      'emoji': '🛍️',
      'range': '5700-7299',
    },
    {
      'id': 8,
      'name': 'Business Services',
      'emoji': '🧑‍💼',
      'range': '7300-7999',
    },
    {
      'id': 9,
      'name': 'Professional Services',
      'emoji': '🧑‍⚕️',
      'range': '8000-8999',
    },
    {
      'id': 10,
      'name': 'Government Services',
      'emoji': '🧑‍⚖️',
      'range': '9000-9999',
    },
    {'id': 11, 'name': 'Airlines', 'emoji': '✈️', 'range': '3000-3299'},
    {'id': 12, 'name': 'Car Rental', 'emoji': '🚘', 'range': '3300-3499'},
    {'id': 13, 'name': 'Lodging', 'emoji': '🏨', 'range': '3500-3999'},
  ];
}

/// Constant MCC Items Data
class MCCData {
  static const List<Map<String, dynamic>> mccItems = [
    // Agricultural Services (0001-1499)
    {
      'mccCode': '742',
      'name': 'Veterinary Services',
      'emoji': '🐾',
      'categoryId': 1,
      'categoryName': 'Agricultural Services',
    },
    {
      'mccCode': '763',
      'name': 'Agricultural Cooperatives',
      'emoji': '🌾',
      'categoryId': 1,
      'categoryName': 'Agricultural Services',
    },
    {
      'mccCode': '780',
      'name': 'Horticultural and Landscaping Services',
      'emoji': '🌱',
      'categoryId': 1,
      'categoryName': 'Agricultural Services',
    },

    // Contracted Services (1500-2999)
    {
      'mccCode': '1520',
      'name': 'General Contractors–Residential and Commercial',
      'emoji': '🏗️',
      'categoryId': 2,
      'categoryName': 'Contracted Services',
    },
    {
      'mccCode': '1711',
      'name': 'Air Conditioning, Heating and Plumbing Contractors',
      'emoji': '🔧',
      'categoryId': 2,
      'categoryName': 'Contracted Services',
    },
    {
      'mccCode': '1731',
      'name': 'Electrical Contractors',
      'emoji': '⚡',
      'categoryId': 2,
      'categoryName': 'Contracted Services',
    },
    {
      'mccCode': '1740',
      'name':
          'Insulation, Masonry, Plastering, Stonework and Tile Setting Contractors',
      'emoji': '🧱',
      'categoryId': 2,
      'categoryName': 'Contracted Services',
    },
    {
      'mccCode': '1750',
      'name': 'Carpentry Contractors',
      'emoji': '🪚',
      'categoryId': 2,
      'categoryName': 'Contracted Services',
    },
    {
      'mccCode': '1761',
      'name': 'Roofing and Siding, Sheet Metal Work Contractors',
      'emoji': '🏠',
      'categoryId': 2,
      'categoryName': 'Contracted Services',
    },
    {
      'mccCode': '1771',
      'name': 'Concrete Work Contractors',
      'emoji': '🚧',
      'categoryId': 2,
      'categoryName': 'Contracted Services',
    },
    {
      'mccCode': '1799',
      'name': 'Contractors, Special Trade Contractors–not elsewhere classified',
      'emoji': '👷',
      'categoryId': 2,
      'categoryName': 'Contracted Services',
    },
    {
      'mccCode': '2741',
      'name': 'Miscellaneous Publishing and Printing',
      'emoji': '📰',
      'categoryId': 2,
      'categoryName': 'Contracted Services',
    },
    {
      'mccCode': '2791',
      'name': 'Typesetting, Plate Making and Related Services',
      'emoji': '🖨️',
      'categoryId': 2,
      'categoryName': 'Contracted Services',
    },
    {
      'mccCode': '2842',
      'name': 'Sanitation, Polishing and Specialty Cleaning Preparations',
      'emoji': '🧼',
      'categoryId': 2,
      'categoryName': 'Contracted Services',
    },

    // Transportation Services (4000-4799)
    {
      'mccCode': '4011',
      'name': 'Railroads–Freight',
      'emoji': '🛤️',
      'categoryId': 3,
      'categoryName': 'Transportation Services',
    },
    {
      'mccCode': '4111',
      'name':
          'Transportation–Suburban and Local Commuter Passenger, including Ferries',
      'emoji': '🚍',
      'categoryId': 3,
      'categoryName': 'Transportation Services',
    },
    {
      'mccCode': '4112',
      'name': 'Passenger Railways',
      'emoji': '🚄',
      'categoryId': 3,
      'categoryName': 'Transportation Services',
    },
    {
      'mccCode': '4119',
      'name': 'Ambulance Services',
      'emoji': '🚑',
      'categoryId': 3,
      'categoryName': 'Transportation Services',
    },
    {
      'mccCode': '4121',
      'name': 'Taxicabs and Limousines',
      'emoji': '🚖',
      'categoryId': 3,
      'categoryName': 'Transportation Services',
    },
    {
      'mccCode': '4131',
      'name': 'Bus Lines',
      'emoji': '🚌',
      'categoryId': 3,
      'categoryName': 'Transportation Services',
    },
    {
      'mccCode': '4214',
      'name':
          'Motor Freight Carriers, Trucking–Local/Long Distance, Moving and Storage Companies, Local Delivery',
      'emoji': '🚚',
      'categoryId': 3,
      'categoryName': 'Transportation Services',
    },
    {
      'mccCode': '4215',
      'name': 'Courier Services–Air and Ground, Freight Forwarders',
      'emoji': '📦',
      'categoryId': 3,
      'categoryName': 'Transportation Services',
    },
    {
      'mccCode': '4225',
      'name':
          'Public Warehousing–Farm Products, Refrigerated Goods, Household Goods Storage',
      'emoji': '📦',
      'categoryId': 3,
      'categoryName': 'Transportation Services',
    },
    {
      'mccCode': '4411',
      'name': 'Cruise Lines',
      'emoji': '🚢',
      'categoryId': 3,
      'categoryName': 'Transportation Services',
    },
    {
      'mccCode': '4457',
      'name': 'Boat Leases and Boat Rentals',
      'emoji': '🛥️',
      'categoryId': 3,
      'categoryName': 'Transportation Services',
    },
    {
      'mccCode': '4468',
      'name': 'Marinas, Marine Service/Supplies',
      'emoji': '⛵',
      'categoryId': 3,
      'categoryName': 'Transportation Services',
    },
    {
      'mccCode': '4511',
      'name': 'Air Carriers, Airlines–not elsewhere classified',
      'emoji': '✈️',
      'categoryId': 3,
      'categoryName': 'Transportation Services',
    },
    {
      'mccCode': '4582',
      'name': 'Airports, Airport Terminals, Flying Fields',
      'emoji': '🛫',
      'categoryId': 3,
      'categoryName': 'Transportation Services',
    },
    {
      'mccCode': '4722',
      'name': 'Travel Agencies and Tour Operators',
      'emoji': '🌍',
      'categoryId': 3,
      'categoryName': 'Transportation Services',
    },
    {
      'mccCode': '4723',
      'name': 'Package Tour Operators (Germany Only)',
      'emoji': '📦',
      'categoryId': 3,
      'categoryName': 'Transportation Services',
    },
    {
      'mccCode': '4761',
      'name': 'Telemarketing of Travel Related Services and Vitamins',
      'emoji': '📞',
      'categoryId': 3,
      'categoryName': 'Transportation Services',
    },
    {
      'mccCode': '4784',
      'name': 'Bridge and Road Fees, Tolls',
      'emoji': '🛣️',
      'categoryId': 3,
      'categoryName': 'Transportation Services',
    },
    {
      'mccCode': '4789',
      'name': 'Transportation Services Not Elsewhere Classified',
      'emoji': '🛣️',
      'categoryId': 3,
      'categoryName': 'Transportation Services',
    },

    // Utility Services (4800-4999)
    {
      'mccCode': '4812',
      'name': 'Telecommunication Equipment Including Telephone Sales',
      'emoji': '📞',
      'categoryId': 4,
      'categoryName': 'Utility Services',
    },
    {
      'mccCode': '4813',
      'name':
          'Key-Entry Telecom Merchant providing single local and long-distance phone calls',
      'emoji': '🔢',
      'categoryId': 4,
      'categoryName': 'Utility Services',
    },
    {
      'mccCode': '4814',
      'name': 'Telecommunication Services including prepaid phone services',
      'emoji': '📶',
      'categoryId': 4,
      'categoryName': 'Utility Services',
    },
    {
      'mccCode': '4816',
      'name': 'Computer Network/Information Services',
      'emoji': '💻',
      'categoryId': 4,
      'categoryName': 'Utility Services',
    },
    {
      'mccCode': '4821',
      'name': 'Telegraph Services',
      'emoji': '📠',
      'categoryId': 4,
      'categoryName': 'Utility Services',
    },
    {
      'mccCode': '4829',
      'name': 'Wire Transfer Money Orders',
      'emoji': '💸',
      'categoryId': 4,
      'categoryName': 'Utility Services',
    },
    {
      'mccCode': '4899',
      'name': 'Cable, Satellite, and Other Pay Television and Radio Services',
      'emoji': '📺',
      'categoryId': 4,
      'categoryName': 'Utility Services',
    },
    {
      'mccCode': '4900',
      'name': 'Utilities–Electric, Gas, Heating Oil, Sanitary, Water',
      'emoji': '💡',
      'categoryId': 4,
      'categoryName': 'Utility Services',
    },

    // Retail Outlet Services (5000-5599)
    {
      'mccCode': '5013',
      'name': 'Motor Vehicle Supplies and New Parts',
      'emoji': '🚗',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5021',
      'name': 'Office and Commercial Furniture',
      'emoji': '🪑',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5039',
      'name': 'Construction Materials Not Elsewhere Classified',
      'emoji': '🧱',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5044',
      'name': 'Office, Photographic, Photocopy and Microfilm Equipment',
      'emoji': '🖨️',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5045',
      'name': 'Computers, Computer Peripheral Equipment, Software',
      'emoji': '💻',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5046',
      'name': 'Commercial Equipment Not Elsewhere Classified',
      'emoji': '🧰',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5047',
      'name':
          'Dental/Laboratory/Medical/Ophthalmic Hospital Equipment and Supplies',
      'emoji': '🏥',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5051',
      'name': 'Metal Service Centers and Offices',
      'emoji': '⛓️',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5065',
      'name': 'Electrical Parts and Equipment',
      'emoji': '🔌',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5072',
      'name': 'Hardware Equipment and Supplies',
      'emoji': '🔩',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5074',
      'name': 'Plumbing and Heating Equipment',
      'emoji': '🚿',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5085',
      'name': 'Industrial Supplies Not Elsewhere Classified',
      'emoji': '📦',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5094',
      'name': 'Precious Stones and Metals, Watches and Jewelry',
      'emoji': '💎',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5099',
      'name': 'Durable Goods Not Elsewhere Classified',
      'emoji': '📦',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5111',
      'name': 'Stationery, Office Supplies, Printing and Writing Paper',
      'emoji': '📦',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5122',
      'name': 'Drugs, Drug Proprietors and Druggists Sundries',
      'emoji': '💊',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5131',
      'name': 'Piece Goods, Notions, and Other Dry Goods',
      'emoji': '📦',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5137',
      'name':
          'Men\'s, Women\'s and Children\'s Uniforms and Commercial Clothing',
      'emoji': '👕',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5139',
      'name': 'Commercial Footware',
      'emoji': '👟',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5169',
      'name': 'Chemicals and Allied Products Not Elsewhere Classified',
      'emoji': '🧴',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5172',
      'name': 'Petroleum and Petroleum Products',
      'emoji': '🛢️',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5192',
      'name': 'Books, Periodicals and Newspapers',
      'emoji': '📚',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5193',
      'name': 'Florists Supplies, Nursery Stock and Flowers',
      'emoji': '🌸',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5198',
      'name': 'Paints, Varnishes and Supplies',
      'emoji': '🎨',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5199',
      'name': 'Non-Durable Goods Not Elsewhere Classified',
      'emoji': '📦',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5200',
      'name': 'Home Supply Warehouse Stores',
      'emoji': '📦',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5211',
      'name': 'Building Materials, Lumber Stores',
      'emoji': '🪵',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5231',
      'name': 'Glass, Paint, Wallpaper Stores',
      'emoji': '🖼️',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5251',
      'name': 'Hardware Stores',
      'emoji': '🔨',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5261',
      'name': 'Lawn and Garden Supply Stores',
      'emoji': '🌿',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5271',
      'name': 'Mobile Home Dealers',
      'emoji': '🏡',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5299',
      'name': 'Warehouse Club Gas',
      'emoji': '📦',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5300',
      'name': 'Wholesale Clubs',
      'emoji': '🛒',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5309',
      'name': 'Duty Free Stores',
      'emoji': '🛃',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5310',
      'name': 'Discount Stores',
      'emoji': '🏷️',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5311',
      'name': 'Department Stores',
      'emoji': '🛍️',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5331',
      'name': 'Variety Stores',
      'emoji': '🛍️',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5399',
      'name': 'Miscellaneous General Merchandise Stores',
      'emoji': '🛒',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5411',
      'name': 'Grocery Stores, Supermarkets',
      'emoji': '🛒',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5422',
      'name': 'Freezer and Locker Meat Provisioners',
      'emoji': '🍖',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5441',
      'name': 'Candy, Nut and Confectionery Stores',
      'emoji': '🍬',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5451',
      'name': 'Dairy Products Stores',
      'emoji': '🥛',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5462',
      'name': 'Bakeries',
      'emoji': '🍞',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5499',
      'name':
          'Miscellaneous Food Stores–Convenience Stores, Markets, Specialty Stores, and Vending Machines',
      'emoji': '🍫',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5511',
      'name':
          'Automobile and Truck Dealers–Sales, Service, Repairs, Parts and Leasing',
      'emoji': '🚗',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5521',
      'name': 'Automobile and Truck Dealers–(Used Only)–Sales',
      'emoji': '🚘',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5532',
      'name': 'Automotive Tire Stores',
      'emoji': '🛞',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5533',
      'name': 'Automotive Parts and Accessories Stores',
      'emoji': '🔧',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5541',
      'name': 'Service Stations (With or Without Ancillary Services)',
      'emoji': '🚗',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5542',
      'name': 'Fuel Dispenser, Automated',
      'emoji': '⛽',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5551',
      'name': 'Boat Dealers',
      'emoji': '🚤',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5561',
      'name': 'Camper Dealers, Recreational and Utility Trailers',
      'emoji': '🚐',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5571',
      'name': 'Motorcycle Shops and Dealers',
      'emoji': '🏍️',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5592',
      'name': 'Motor Home Dealers',
      'emoji': '🚐',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5598',
      'name': 'Snowmobile Dealers',
      'emoji': '🛷',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },
    {
      'mccCode': '5599',
      'name':
          'Miscellaneous Automotive, Aircraft, and Farm Equipment Dealers–Not Elsewhere Classified',
      'emoji': '🚜',
      'categoryId': 5,
      'categoryName': 'Retail Outlet Services',
    },

    // Clothing Stores (5600-5699)
    {
      'mccCode': '5611',
      'name': 'Men\'s and Boys\' Clothing and Accessories Stores',
      'emoji': '👔',
      'categoryId': 6,
      'categoryName': 'Clothing Stores',
    },
    {
      'mccCode': '5621',
      'name': 'Women\'s Ready to Wear Stores',
      'emoji': '👗',
      'categoryId': 6,
      'categoryName': 'Clothing Stores',
    },
    {
      'mccCode': '5631',
      'name': 'Women\'s Accessory and Specialty Stores',
      'emoji': '💄',
      'categoryId': 6,
      'categoryName': 'Clothing Stores',
    },
    {
      'mccCode': '5641',
      'name': 'Children\'s and Infants\' Wear Stores',
      'emoji': '👶',
      'categoryId': 6,
      'categoryName': 'Clothing Stores',
    },
    {
      'mccCode': '5651',
      'name': 'Family Clothing Stores',
      'emoji': '👪',
      'categoryId': 6,
      'categoryName': 'Clothing Stores',
    },
    {
      'mccCode': '5655',
      'name': 'Sports Apparel, and Riding Apparel Stores',
      'emoji': '🏃',
      'categoryId': 6,
      'categoryName': 'Clothing Stores',
    },
    {
      'mccCode': '5661',
      'name': 'Shoe Stores',
      'emoji': '👟',
      'categoryId': 6,
      'categoryName': 'Clothing Stores',
    },
    {
      'mccCode': '5681',
      'name': 'Furriers and Fur Shops',
      'emoji': '🐺',
      'categoryId': 6,
      'categoryName': 'Clothing Stores',
    },
    {
      'mccCode': '5691',
      'name': 'Men\'s and Women\'s Clothing Stores',
      'emoji': '👔',
      'categoryId': 6,
      'categoryName': 'Clothing Stores',
    },
    {
      'mccCode': '5697',
      'name': 'Alterations, Mending, Seamstresses, Tailors',
      'emoji': '🧵',
      'categoryId': 6,
      'categoryName': 'Clothing Stores',
    },
    {
      'mccCode': '5698',
      'name': 'Wig and Toupee Shops',
      'emoji': '💇',
      'categoryId': 6,
      'categoryName': 'Clothing Stores',
    },
    {
      'mccCode': '5699',
      'name': 'Accessory and Apparel Stores–Miscellaneous',
      'emoji': '🛍️',
      'categoryId': 6,
      'categoryName': 'Clothing Stores',
    },

    // Miscellaneous Stores (5700-7299)
    {
      'mccCode': '5712',
      'name':
          'Equipment, Furniture and Home Furnishings Stores (except Appliances)',
      'emoji': '🛋️',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5713',
      'name': 'Floor Covering Stores',
      'emoji': '🧱',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5714',
      'name': 'Drapery, Upholstery and Window Coverings Stores',
      'emoji': '🪟',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5718',
      'name': 'Fireplace, Fireplace Screens and Accessories Stores',
      'emoji': '🔥',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5719',
      'name': 'Miscellaneous House Furnishing Specialty Shops',
      'emoji': '🏠',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5722',
      'name': 'Household Appliance Stores',
      'emoji': '🧺',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5732',
      'name': 'Electronics Sales',
      'emoji': '📺',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5733',
      'name': 'Music Stores–Musical Instruments, Pianos and Sheet Music',
      'emoji': '🎵',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5734',
      'name': 'Computer Software Stores',
      'emoji': '💻',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5735',
      'name': 'Record Shops',
      'emoji': '🎧',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5811',
      'name': 'Caterers',
      'emoji': '🍲',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5812',
      'name': 'Eating Places and Restaurants',
      'emoji': '🍽️',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5813',
      'name':
          'Bars, Cocktail Lounges, Discotheques, Nightclubs and Taverns–Drinking Places (Alcoholic Beverages)',
      'emoji': '🍺',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5814',
      'name': 'Fast Food Restaurants',
      'emoji': '🍔',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5815',
      'name': 'Digital Goods: Books, Movies, Music',
      'emoji': '📚',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5816',
      'name': 'Digital Goods: Games',
      'emoji': '🎮',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5817',
      'name': 'Digital Goods: Applications (Excludes Games)',
      'emoji': '📱',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5818',
      'name': 'Digital Goods: Large Digital Goods Merchant',
      'emoji': '💾',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5912',
      'name': 'Drug Stores and Pharmacies',
      'emoji': '💊',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5921',
      'name': 'Package Stores–Beer, Wine and Liquor',
      'emoji': '🍷',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5931',
      'name': 'Second Hand Stores, Used Merchandise Stores',
      'emoji': '🛒',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5932',
      'name': 'Antique Shops–Sales, Repairs and Restoration Services',
      'emoji': '🕰️',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5933',
      'name': 'Pawn Shops',
      'emoji': '💼',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5935',
      'name': 'Wrecking and Salvage Yards',
      'emoji': '🚛',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5937',
      'name': 'Antique Reproduction Stores',
      'emoji': '🏺',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5940',
      'name': 'Bicycle Shops–Sales and Service',
      'emoji': '🚴',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5941',
      'name': 'Sporting Goods Stores',
      'emoji': '🏆',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5942',
      'name': 'Book Stores',
      'emoji': '📖',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5943',
      'name': 'Office, School Supply and Stationery Stores',
      'emoji': '🖋️',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5944',
      'name': 'Clock, Jewelry, Watch and Silverware Stores',
      'emoji': '⌚',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5945',
      'name': 'Game, Toy and Hobby Shops',
      'emoji': '🧩',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5946',
      'name': 'Camera and Photographic Supply Stores',
      'emoji': '📸',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5947',
      'name': 'Card, Gift, Novelty and Souvenir Shops',
      'emoji': '🎁',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5948',
      'name': 'Leather Goods and Luggage Stores',
      'emoji': '🧳',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5949',
      'name': 'Fabric, Needlework, Piece Goods and Sewing Stores',
      'emoji': '🧵',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5950',
      'name': 'Crystal and Glassware Stores',
      'emoji': '🍾',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5960',
      'name': 'Direct Marketing Insurance Services',
      'emoji': '🛡️',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5961',
      'name': 'Mail Order Houses Including Catalog Order Stores',
      'emoji': '📦',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5962',
      'name': 'Direct Marketing–Travel Related Arrangement Services',
      'emoji': '✈️',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5963',
      'name': 'Door-to-Door Sales',
      'emoji': '🚪',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5964',
      'name': 'Direct Marketing–Catalog Merchants',
      'emoji': '📚',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5965',
      'name': 'Direct Marketing–Combination Catalog and Retail Merchant',
      'emoji': '🛒',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5966',
      'name': 'Direct Marketing–Outbound Telemarketing Merchants',
      'emoji': '📞',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5967',
      'name': 'Direct Marketing–Inbound Telemarketing Merchants',
      'emoji': '📞',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5968',
      'name': 'Direct Marketing–Continuity/Subscription Merchants',
      'emoji': '🔁',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5969',
      'name':
          'Direct Marketing–Other Direct Marketers–Not Elsewhere Classified',
      'emoji': '📢',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5970',
      'name': 'Artist Supply Stores, Craft Shops',
      'emoji': '🎨',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5971',
      'name': 'Art Dealers and Galleries',
      'emoji': '🖼️',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5972',
      'name': 'Stamp and Coin Stores–Philatelic and Numismatic Supplies',
      'emoji': '🪙',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5973',
      'name': 'Religious Goods Stores',
      'emoji': '🙏',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5974',
      'name': 'Rubber Stamp Store',
      'emoji': '🖋️',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5975',
      'name': 'Hearing Aids–Sales, Service, Supply Stores',
      'emoji': '🎧',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5976',
      'name': 'Orthopedic Goods–Artificial Limb Stores',
      'emoji': '🦿',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5977',
      'name': 'Cosmetic Stores',
      'emoji': '💄',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5978',
      'name': 'Typewriter Stores–Rentals, Sales, Service',
      'emoji': '🖥️',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5983',
      'name': 'Fuel Dealers–Coal, Fuel Oil, Liquefied Petroleum, Wood',
      'emoji': '🔥',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5992',
      'name': 'Florists',
      'emoji': '🌸',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5993',
      'name': 'Cigar Stores and Stands',
      'emoji': '🚬',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5994',
      'name': 'News Dealers and Newsstands',
      'emoji': '📰',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5995',
      'name': 'Pet Shops, Pet Food and Supplies',
      'emoji': '🐶',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5996',
      'name': 'Swimming Pools–Sales and Supplies',
      'emoji': '🏊',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5997',
      'name': 'Electric Razor Stores–Sales and Service',
      'emoji': '🚿',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5998',
      'name': 'Tent and Awning Shops',
      'emoji': '🏕️',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '5999',
      'name': 'Miscellaneous and Specialty Retail Stores',
      'emoji': '🛍️',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '6010',
      'name': 'Member Financial Institution–Manual Cash Disbursements',
      'emoji': '💰',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '6011',
      'name': 'Member Financial Institution–Automated Cash Disbursements',
      'emoji': '💳',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '6012',
      'name': 'Member Financial Institution–Merchandise And Services',
      'emoji': '🛒',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '6050',
      'name': 'Quasi Cash–Member Financial Institution',
      'emoji': '💸',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '6051',
      'name': 'Quasi Cash–Merchant',
      'emoji': '💸',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '6211',
      'name': 'Securities–Brokers and Dealers',
      'emoji': '📈',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '6236',
      'name': 'Aero Servicio Carabobo',
      'emoji': '✈️',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '6300',
      'name': 'Insurance Sales, Underwriting and Premiums',
      'emoji': '🛡️',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '6381',
      'name': 'Insurance–Premiums',
      'emoji': '💼',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '6513',
      'name': 'Real Estate Agents and Managers–Rentals',
      'emoji': '🏡',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '6529',
      'name': 'Remote Stored Value Load — Member Financial Institution',
      'emoji': '💾',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '6530',
      'name': 'Remove Stored Value Load — Merchant',
      'emoji': '💸',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '6535',
      'name': 'Value Purchase–Member Financial Institution',
      'emoji': '💰',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '6536',
      'name': 'MoneySend Intracountry M',
      'emoji': '💸',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '6537',
      'name': 'MoneySend Intercountry M',
      'emoji': '💸',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '6538',
      'name': 'MoneySend Funding M',
      'emoji': '💸',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '6539',
      'name': 'Funding Transaction (Excluding MoneySend) M',
      'emoji': '💰',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '6540',
      'name':
          'POI (Point of Interaction) Funding Transactions (Excluding MoneySend) M',
      'emoji': '💳',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '6611',
      'name': 'Overpayments',
      'emoji': '💸',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '6760',
      'name': 'Savings Bonds',
      'emoji': '📈',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '7011',
      'name': 'Lodging–Hotels, Motels, Resorts–not elsewhere classified',
      'emoji': '🏨',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '7012',
      'name': 'Timeshares',
      'emoji': '🏠',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '7032',
      'name': 'Sporting and Recreational Camps',
      'emoji': '🏕️',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '7033',
      'name': 'Campgrounds and Trailer Parks',
      'emoji': '🏕️',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '7210',
      'name': 'Cleaning, Garment and Laundry Services',
      'emoji': '🧼',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '7211',
      'name': 'Laundry Services–Family and Commercial',
      'emoji': '🧺',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '7216',
      'name': 'Dry Cleaners',
      'emoji': '🧺',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '7217',
      'name': 'Carpet and Upholstery Cleaning',
      'emoji': '🧽',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '7221',
      'name': 'Photographic Studios',
      'emoji': '📸',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '7230',
      'name': 'Barber and Beauty Shops',
      'emoji': '💇',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '7251',
      'name': 'Hat Cleaning Shops, Shoe Repair Shops, Shoe Shine Parlors',
      'emoji': '👞',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '7261',
      'name': 'Funeral Service and Crematories',
      'emoji': '🕯️',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '7273',
      'name': 'Dating Services',
      'emoji': '💘',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '7276',
      'name': 'Tax Preparation Service',
      'emoji': '🧾',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '7277',
      'name': 'Debt, Marriage, Personal–Counseling Services',
      'emoji': '🧠',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '7278',
      'name': 'Buying/Shopping Clubs, Services',
      'emoji': '🛒',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '7280',
      'name': 'Hospital Patient-Personal Funds Withdrawal',
      'emoji': '💉',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '7295',
      'name': 'Babysitting Services',
      'emoji': '👶',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '7296',
      'name': 'Clothing Rental–Costumes, Uniforms and Formal Wear',
      'emoji': '👔',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '7297',
      'name': 'Massage Parlors',
      'emoji': '🧖',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '7298',
      'name': 'Health and Beauty Spas',
      'emoji': '🛀',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },
    {
      'mccCode': '7299',
      'name': 'Other Services–Not Elsewhere Classified',
      'emoji': '🛠️',
      'categoryId': 7,
      'categoryName': 'Miscellaneous Stores',
    },

    // Business Services (7300-7999)
    {
      'mccCode': '7311',
      'name': 'Advertising Services',
      'emoji': '📢',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7321',
      'name': 'Consumer Credit Reporting Agencies',
      'emoji': '📊',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7332',
      'name': 'Blueprinting and Photocopying Services',
      'emoji': '🖋️',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7333',
      'name': 'Commercial Art, Graphics, Photography',
      'emoji': '🎨',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7338',
      'name': 'Quick Copy, Reproduction and Blueprinting Services',
      'emoji': '📄',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7339',
      'name': 'Stenographic and Secretarial Support Services',
      'emoji': '🖊️',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7342',
      'name': 'Exterminating and Disinfecting Services',
      'emoji': '🧫',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7349',
      'name': 'Cleaning and Maintenance, Janitorial Services',
      'emoji': '🧼',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7361',
      'name': 'Employment Agencies and Temporary Help Services',
      'emoji': '👥',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7372',
      'name':
          'Computer Programming, Data Processing and Integrated System Design Services',
      'emoji': '💻',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7375',
      'name': 'Information Retrieval Services',
      'emoji': '🔍',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7379',
      'name':
          'Computer Maintenance, Repair And Services–Not Elsewhere Classified',
      'emoji': '🛠️',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7392',
      'name': 'Consulting, Management and Public Relations Services',
      'emoji': '🤝',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7393',
      'name':
          'Detective Agencies, Protective Agencies, Security Services including Armored Cars, Guard Dogs',
      'emoji': '🛡️',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7394',
      'name':
          'Equipment Rental and Leasing Services, Furniture Rental, Tool Rental',
      'emoji': '🚚',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7395',
      'name': 'Photo Developing, Photofinishing Laboratories',
      'emoji': '📸',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7399',
      'name': 'Business Services Not Elsewhere Classified',
      'emoji': '🏢',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7512',
      'name': 'Automobile Rental Agency–Not Elsewhere Classified',
      'emoji': '🚗',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7513',
      'name': 'Truck Rental',
      'emoji': '🚛',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7519',
      'name': 'Motor Home and Recreational Vehicle Rental',
      'emoji': '🚐',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7523',
      'name': 'Automobile Parking Lots and Garages',
      'emoji': '🅿️',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7524',
      'name': 'Express Payment Service Merchants–Parking Lots and Garages',
      'emoji': '🅿️',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7531',
      'name': 'Automotive Body Repair Shops',
      'emoji': '🛠️',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7534',
      'name': 'Tire Retreading and Repair Shops',
      'emoji': '🔧',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7535',
      'name': 'Automotive Paint Shops',
      'emoji': '🚗',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7538',
      'name': 'Automotive Service Shops',
      'emoji': '🚗',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7542',
      'name': 'Car Washes',
      'emoji': '🚿',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7549',
      'name': 'Towing Services',
      'emoji': '🛻',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7622',
      'name': 'Electronic Repair Shops',
      'emoji': '📱',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7623',
      'name': 'Air Conditioning and Refrigeration Repair Shops',
      'emoji': '❄️',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7629',
      'name': 'Appliance Repair Shops, Electrical and Small',
      'emoji': '🛠️',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7631',
      'name': 'Clock, Jewelry and Watch Repair Shops',
      'emoji': '⌚',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7641',
      'name': 'Furniture–Reupholstery, Repair and Refinishing',
      'emoji': '🛋️',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7692',
      'name': 'Welding Repair',
      'emoji': '🛠️',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7699',
      'name': 'Miscellaneous Repair Shops and Related Services',
      'emoji': '🛠️',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7800',
      'name': 'Government Owned Lottery',
      'emoji': '🎫',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7801',
      'name': 'Government-Licensed Casinos (Online or Internet Gambling)',
      'emoji': '🎰',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7802',
      'name': 'Government-Licensed Horse/Dog Racing',
      'emoji': '🐎',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7829',
      'name': 'Motion Picture and Video Tape Production and Distribution',
      'emoji': '🎬',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7832',
      'name': 'Motion Picture Theaters',
      'emoji': '🎥',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7833',
      'name': 'Express Payment Service — Motion Picture Theater',
      'emoji': '💳',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7841',
      'name': 'DVD/Video Tape Rental Stores',
      'emoji': '📼',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7911',
      'name': 'Dance Halls, Schools and Studios',
      'emoji': '💃',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7922',
      'name': 'Theatrical Producers (Except Motion Pictures), Ticket Agencies',
      'emoji': '🎭',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7929',
      'name':
          'Bands, Orchestras and Miscellaneous Entertainers– Not Elsewhere Classified',
      'emoji': '🎵',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7932',
      'name': 'Pool and Billiard Establishments',
      'emoji': '🎯',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7933',
      'name': 'Bowling Alleys',
      'emoji': '🎳',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7941',
      'name':
          'Athletic Fields, Commercial Sports, Professional Sports Clubs, Sports Promoters',
      'emoji': '🏆',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7991',
      'name': 'Tourist Attractions and Exhibits',
      'emoji': '🏞️',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7992',
      'name': 'Golf Courses, Public',
      'emoji': '🏌️',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7993',
      'name': 'Video Amusement Game Supplies',
      'emoji': '🎮',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7994',
      'name': 'Video Game Arcades and Establishments',
      'emoji': '🕹️',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7995',
      'name': 'Gambling Transactions Betting',
      'emoji': '🎲',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7996',
      'name':
          'Amusement Parks, Carnivals, Circuses, Carnivals, Fortune Tellers',
      'emoji': '🎪',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7997',
      'name':
          'Clubs–Country Clubs, Membership (Athletic, Recreation, Sports), Private Golf Courses',
      'emoji': '🏌️',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7998',
      'name': 'Aquariums, Dolphinariums, Zoos and Seaquariums',
      'emoji': '🐒',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },
    {
      'mccCode': '7999',
      'name': 'Recreation Services–Not Elsewhere Classified',
      'emoji': '🎉',
      'categoryId': 8,
      'categoryName': 'Business Services',
    },

    // Professional Services (8000-8999)
    {
      'mccCode': '8011',
      'name': 'Doctors–not elsewhere classified',
      'emoji': '🩺',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8021',
      'name': 'Dentists and Orthodontists',
      'emoji': '🦷',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8031',
      'name': 'Osteopathic Physicians',
      'emoji': '🧠',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8041',
      'name': 'Chiropractors',
      'emoji': '🧘',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8042',
      'name': 'Optometrists and Ophthalmologists',
      'emoji': '👁️',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8043',
      'name': 'Opticians, Optical Goods and Eyeglasses',
      'emoji': '👓',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8044',
      'name': 'Optical Goods and Eyeglasses TSYS',
      'emoji': '👓',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8049',
      'name': 'Chiropodists, Podiatrists',
      'emoji': '🦶',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8050',
      'name': 'Nursing and Personal Care Facilities',
      'emoji': '🏥',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8062',
      'name': 'Hospitals',
      'emoji': '🏥',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8071',
      'name': 'Dental and Medical Laboratories',
      'emoji': '🧫',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8099',
      'name': 'Health Practitioners, Medical Services–Not Elsewhere Classified',
      'emoji': '🩺',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8111',
      'name': 'Attorneys, Legal Services',
      'emoji': '📜',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8211',
      'name': 'Schools, Elementary and Secondary',
      'emoji': '🏫',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8220',
      'name':
          'Colleges, Universities, Professional Schools and Junior Colleges',
      'emoji': '🎓',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8241',
      'name': 'Schools, Correspondence',
      'emoji': '🏫',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8244',
      'name': 'Schools, Business and Secretarial',
      'emoji': '🏫',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8249',
      'name': 'Schools, Trade and Vocational',
      'emoji': '🏫',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8299',
      'name': 'Schools And Educational Services–Not Elsewhere Classified',
      'emoji': '🏫',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8351',
      'name': 'Child Care Services',
      'emoji': '👶',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8398',
      'name': 'Organizations, Charitable and Social Service',
      'emoji': '❤️',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8641',
      'name': 'Associations–Civic, Social and Fraternal',
      'emoji': '🤝',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8651',
      'name': 'Organizations, Political',
      'emoji': '🗳️',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8661',
      'name': 'Organizations, Religious',
      'emoji': '🙏',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8675',
      'name': 'Automobile Associations',
      'emoji': '🚗',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8699',
      'name': 'Organizations, Membership–Not Elsewhere Classified',
      'emoji': '🤝',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8734',
      'name': 'Testing Laboratories (Non-Medical)',
      'emoji': '🧪',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8743',
      'name': 'Testing Laboratories (Non-Medical) TSYS',
      'emoji': '🧪',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8911',
      'name': 'Architectural, Engineering and Surveying Services',
      'emoji': '🏗️',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8931',
      'name': 'Accounting, Auditing and Bookkeeping Services',
      'emoji': '📊',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },
    {
      'mccCode': '8999',
      'name': 'Professional Services–Not Elsewhere Classified',
      'emoji': '🛠️',
      'categoryId': 9,
      'categoryName': 'Professional Services',
    },

    // Government Services (9000-9999)
    {
      'mccCode': '9034',
      'name': 'I-Purchasing Pilot TSYS',
      'emoji': '🔄',
      'categoryId': 10,
      'categoryName': 'Government Services',
    },
    {
      'mccCode': '9211',
      'name': 'Court Costs Including Alimony and Child Support',
      'emoji': '🏛️',
      'categoryId': 10,
      'categoryName': 'Government Services',
    },
    {
      'mccCode': '9222',
      'name': 'Fines',
      'emoji': '🚨',
      'categoryId': 10,
      'categoryName': 'Government Services',
    },
    {
      'mccCode': '9223',
      'name': 'Bail and Bond Payments',
      'emoji': '🛡️',
      'categoryId': 10,
      'categoryName': 'Government Services',
    },
    {
      'mccCode': '9311',
      'name': 'Tax Payments',
      'emoji': '💰',
      'categoryId': 10,
      'categoryName': 'Government Services',
    },
    {
      'mccCode': '9399',
      'name': 'Government Services–Not Elsewhere Classified',
      'emoji': '🏛️',
      'categoryId': 10,
      'categoryName': 'Government Services',
    },
    {
      'mccCode': '9401',
      'name': 'I-Purchasing Pilot TSYS',
      'emoji': '🔄',
      'categoryId': 10,
      'categoryName': 'Government Services',
    },
    {
      'mccCode': '9402',
      'name': 'Postal Services–Government Only',
      'emoji': '📬',
      'categoryId': 10,
      'categoryName': 'Government Services',
    },
    {
      'mccCode': '9405',
      'name': 'Intra-Government Purchases–Government Only',
      'emoji': '🏢',
      'categoryId': 10,
      'categoryName': 'Government Services',
    },
    {
      'mccCode': '9700',
      'name': 'Automated Referral Service V',
      'emoji': '🔄',
      'categoryId': 10,
      'categoryName': 'Government Services',
    },
    {
      'mccCode': '9701',
      'name': 'Visa Credential Server V',
      'emoji': '🔐',
      'categoryId': 10,
      'categoryName': 'Government Services',
    },
    {
      'mccCode': '9702',
      'name': 'GCAS Emergency Services V',
      'emoji': '🚨',
      'categoryId': 10,
      'categoryName': 'Government Services',
    },
    {
      'mccCode': '9751',
      'name': 'UK Supermarkets, Electronic Hot File TSYS',
      'emoji': '🛒',
      'categoryId': 10,
      'categoryName': 'Government Services',
    },
    {
      'mccCode': '9752',
      'name': 'UK Petrol Stations, Electronic Hot File TSYS',
      'emoji': '⛽',
      'categoryId': 10,
      'categoryName': 'Government Services',
    },
    {
      'mccCode': '9754',
      'name': 'Gambling-Horse, Dog Racing, State Lottery M',
      'emoji': '🎲',
      'categoryId': 10,
      'categoryName': 'Government Services',
    },
    {
      'mccCode': '9950',
      'name': 'Intra-Company Purchases V,M',
      'emoji': '🔄',
      'categoryId': 10,
      'categoryName': 'Government Services',
    },
  ];

  /// Convert constant MCC data to MCCItem objects
  static List<MCCItem> getMCCItems() {
    return mccItems.map((item) {
      return MCCItem(
        id: int.tryParse(item['mccCode'] ?? '0'),
        name: item['name'] ?? '',
        mccCode: item['mccCode'],
        emoji: item['emoji'],
        categoryId: item['categoryId'] ?? 0,
        categoryName: item['categoryName'] ?? '',
      );
    }).toList();
  }

  /// Convert constant category data to MCCCategory objects
  static List<MCCCategory> getCategories() {
    return MCCCategories.categories.map((cat) {
      return MCCCategory(
        id: cat['id'],
        name: cat['name'] ?? '',
        emoji: cat['emoji'],
      );
    }).toList();
  }
}
